import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import "../sass/index.scss";
import { ThemeProvider } from "../../context/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <ThemeProvider>
            <AuthProvider>
              <div className="layout-container">
                <Navbar />
                <div>{children}</div>
                <Footer />
              </div>
            </AuthProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
